In [4]:
using LFAToolkit
using LinearAlgebra

In [56]:
# setup
finep = 6
coarsep = 2
numbercomponents = 1
dimension = 3
mesh = Mesh3D(1.0, 1.0, 1.0)

ctofbasis = TensorH1LagrangePProlongationBasis(coarsep, finep, numbercomponents, dimension)

# diffusion operators
finediffusion = GalleryOperator("diffusion", finep, finep+1, mesh)
coarsediffusion = GalleryOperator("diffusion", coarsep, finep+1, mesh)

# Jacobi smoother
jacobi = Jacobi(finediffusion)

# p-multigrid preconditioner
multigrid = PMultigrid(finediffusion, coarsediffusion, jacobi, [ctofbasis])

p-multigrid preconditioner

In [57]:
# full operator symbols
numberruns = 25
θ_min = -π/2
θ_max = 3π/2
ω_min = 0.0
ω_max = 1.1

# compute and plot smoothing factor
# setup
maxeigenvalue = zeros((finep-1)^dimension)

# compute
for i in 1:numberruns, j in 1:numberruns, k in 1:numberruns
    θ = [
        θ_min + (θ_max - θ_min)*i/numberruns,
        θ_min + (θ_max - θ_min)*j/numberruns,
        θ_min + (θ_max - θ_min)*k/numberruns,
        ]
    if sqrt(abs(θ[1])^2 + abs(θ[2])^2 + abs(θ[3])^2) >  π/128
        A = computesymbols(multigrid, [1.0], [1, 1], θ)
        currenteigenvalues = sort([abs(val) for val in eigvals(A)])
        maxeigenvalue = [max(currenteigenvalues[i], maxeigenvalue[i]) for i in 1:(finep-1)^dimension]
    end
end

In [25]:
maxeigenvalue

64-element Array{Float64,1}:
 6.234182574603039e-12
 0.0013083727497541523
 0.0043872416709085605
 0.004760380895055032
 0.0057236165522319095
 0.007424817222097008
 0.007851276796613139
 0.009746820357477542
 0.010549561131094943
 0.011393086469767433
 0.012806216265689889
 0.013309370834655746
 0.01448830633087215
 ⋮
 0.3708688833600361
 0.4022774445882951
 0.5155656929788817
 0.5155656929788849
 0.5493353513900792
 0.6132036348758616
 0.652547809145852
 0.6675981390982542
 0.793501147501895
 0.7935161186032523
 0.8927507455074997
 1.4345148173746072

In [19]:
maxeigenvalue

27-element Array{Float64,1}:
 1.716060548250597e-12
 0.004919742387128298
 0.00600488683698788
 0.010201937992279166
 0.010201937992279229
 0.010205430471698399
 0.03400387115250567
 0.04185503371066139
 0.04191118466813063
 0.04191118466813078
 0.04250855381950474
 0.048025909428484136
 0.08299507152492237
 ⋮
 0.11236051616444943
 0.12995178848792965
 0.19079722314357603
 0.1907972231435766
 0.20035160265718874
 0.24251373971510767
 0.2522879588845543
 0.291225468223933
 0.31989261453209833
 0.4033282196118655
 0.5615374061797727
 0.9771278831823211

In [22]:
maxeigenvalue

8-element Array{Float64,1}:
 1.234704137012835e-12
 0.023326363024872145
 0.027699423720740222
 0.05562533899938285
 0.06236289632581674
 0.09201263522608409
 0.13299664975732486
 0.31141569180794737

In [32]:
maxeigenvalue

64-element Array{Float64,1}:
 1.547692222373154e-16
 6.295488949836387e-16
 1.329163841933331e-15
 1.435439261293575e-15
 1.906324718033283e-15
 1.947777112733196e-15
 4.419224588168184e-15
 3.3983801728740554e-12
 0.0029507669125171205
 0.004388507509055511
 0.0073509101665326605
 0.007959367043576306
 0.00935392177542924
 ⋮
 0.2711412799450402
 0.27410479637194773
 0.2922374892604545
 0.29944264655796426
 0.30907793996304406
 0.3666963593007576
 0.376465946174119
 0.4183722341677957
 0.7921848231986683
 0.7922049282253093
 0.8927202219815641
 1.434503405707822

In [44]:
maxeigenvalue

27-element Array{Float64,1}:
 6.300359764509246e-16
 9.615839374783e-16
 1.1036545131414104e-15
 3.237874904165265e-15
 6.519096956266479e-15
 1.64919939314296e-14
 1.7946216754957126e-14
 4.4852772275730204e-14
 0.007398554631212121
 0.008132279727406955
 0.015483899790119184
 0.020960131523944672
 0.028353749727195537
 ⋮
 0.05252245053953228
 0.05707447971699375
 0.06763843155307617
 0.08532083106259904
 0.09280356372264442
 0.12256593843046835
 0.20018965992361998
 0.20020771776849858
 0.20410317346625254
 0.31945741969174657
 0.31945741969175595
 0.3776763358297345

In [51]:
maxeigenvalue

125-element Array{Float64,1}:
 1.1767307241123423e-15
 3.486690583780685e-15
 4.1317929869447475e-15
 6.449559831129659e-15
 6.551638324989093e-15
 6.872371176940844e-15
 7.998152704370948e-15
 8.855714734183755e-15
 8.859880087927867e-15
 9.005961922582767e-15
 1.3275067587676899e-14
 1.4051659970427908e-14
 1.5837708743650524e-14
 ⋮
 0.43507325771564
 0.5241840783640384
 0.5293046322697804
 0.5383019396162081
 0.5463042871883217
 0.9857533391919219
 0.9864789610114392
 0.9864789610114638
 1.0052615770738815
 1.0085069203596844
 1.2013666219778991
 1.6634295569720927

In [47]:
maxeigenvalue

64-element Array{Float64,1}:
 3.517471474918366e-17
 2.1245852183760008e-16
 3.705095784430323e-16
 3.778378735095786e-16
 4.959637342866804e-16
 1.0614896529291057e-15
 1.1651622777202888e-15
 2.0524117128398853e-15
 2.1241612016020625e-15
 3.2772039855345004e-15
 3.3507772995217808e-15
 4.092722504218014e-15
 4.696797573407917e-15
 ⋮
 0.18667407560366042
 0.1958890357570962
 0.2162450745137277
 0.21624507451374658
 0.23199960088595284
 0.23861191245212443
 0.2686422538316913
 0.272356227765766
 0.2816046663659054
 0.39376095885983114
 0.39393664505554893
 0.3953680474083098

In [55]:
maxeigenvalue

125-element Array{Float64,1}:
 9.425430240490978e-16
 3.4254518970972287e-15
 3.5241907260014724e-15
 5.816700102828751e-15
 5.9772805889158415e-15
 6.481382959666829e-15
 7.680278247127551e-15
 6.9596490032602116e-12
 0.0003645913511367214
 0.0011884087029590087
 0.001603899493221634
 0.0020357628030274154
 0.002062517698615379
 ⋮
 0.5295235567285153
 0.541045692016824
 0.652275354212914
 0.6522966188345998
 0.6522966188346
 0.993312796921996
 0.9949525999140314
 0.994952599914047
 1.00754122434588
 1.0103817443881995
 1.203482950380546
 1.6634374036585262

In [58]:
maxeigenvalue

125-element Array{Float64,1}:
 6.6998207885761245e-12
 0.00032075868460951435
 0.0007179279327454127
 0.0010345200218892646
 0.0010859972815475036
 0.0015566444270119627
 0.0021096842975218285
 0.002392094958866554
 0.003968602146108527
 0.004622988820757441
 0.0050547463061582825
 0.006833835211330266
 0.0071201779318284105
 ⋮
 0.6515463015218126
 0.6515486664072521
 0.7430255223745853
 0.7587693046529523
 0.8126939417992586
 0.9946568514149535
 0.9952396805118412
 0.9952396805118557
 1.0179730899847725
 1.018157077853667
 1.208739983392569
 1.6710909316057463